version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: movie_rating_db
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
      POSTGRES_DB: movie_rating_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie_user -d movie_rating_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

